import { createGame, update } from './engine.js';
import { render } from './render.js';
import { AudioSystem } from './audio.js';
const $=id=>document.getElementById(id), canvas=$('game'),ctx=canvas.getContext('2d',{alpha:false});
const audio=new AudioSystem(), reduced=matchMedia('(prefers-reduced-motion: reduce)');
let game=createGame({difficulty:'normal',seed:17}), mode='title', last=0,accumulator=0,best=0,hudTime=0,tipTimer=0;
try{best=Number(localStorage.getItem('neon-alley-best'))||0;audio.setMuted(localStorage.getItem('neon-alley-muted')==='true');}catch{}
const keys=new Set(), touches=new Map();
const mapping={ArrowLeft:'left',KeyA:'left',ArrowRight:'right',KeyD:'right',ArrowUp:'up',KeyW:'up',ArrowDown:'down',KeyS:'down',KeyJ:'punch',KeyK:'kick',Space:'jump',KeyL:'grab'};
function clearInput(){keys.clear();touches.clear();document.querySelectorAll('[data-control]').forEach(b=>b.classList.remove('held'));}
function input(){const a={};keys.forEach(k=>a[k]=true);touches.forEach(k=>a[k]=true);return a;}
function soundLabel(){$('mute').textContent=audio.muted?'♫ 音效關閉':'♪ 音效開啟';$('mute').setAttribute('aria-pressed',String(audio.muted));}
function mute(){audio.unlock();audio.setMuted(!audio.muted);soundLabel();try{localStorage.setItem('neon-alley-muted',String(audio.muted));}catch{}}
function start(){clearInput();game=createGame({difficulty:$('difficulty').value,seed:17});mode='playing';accumulator=0;last=performance.now();$('overlay').hidden=true;$('pause').disabled=false;$('pause').textContent='Ⅱ 暫停';$('combat-tip').textContent='J 連拳 · K 踢擊 · 跳躍後 K 飛踢';tipTimer=6;audio.unlock();audio.setRunning(true);canvas.focus({preventScroll:true});refreshHUD();}
function showModal(kicker,title,copy,resume=false){$('intro').hidden=true;$('modal').hidden=false;$('overlay').hidden=false;$('modal-kicker').textContent=kicker;$('modal-title').textContent=title;$('modal-copy').textContent=copy;$('resume').hidden=!resume;}
function pause(){if(mode==='playing'){mode='paused';clearInput();audio.setRunning(false);showModal('TAKE A BREATHER','訊號暫停',`已保留目前進度。\n${game.stageName} · 第 ${game.wave+1} 波`,true);$('pause').textContent='▶ 繼續';$('resume').focus({preventScroll:true});}else if(mode==='paused'){mode='playing';last=performance.now();accumulator=0;$('overlay').hidden=true;clearInput();audio.unlock();audio.setRunning(true);$('pause').textContent='Ⅱ 暫停';canvas.focus({preventScroll:true});}refreshHUD();}
function title(){mode='title';clearInput();audio.setRunning(false);game=createGame({difficulty:$('difficulty').value,seed:17});$('intro').hidden=false;$('modal').hidden=true;$('overlay').hidden=false;$('pause').disabled=true;$('pause').textContent='Ⅱ 暫停';$('combat-tip').textContent='';$('start').focus({preventScroll:true});refreshHUD();}
function finish(){mode=game.status;clearInput();audio.setRunning(false);best=Math.max(best,game.score);try{localStorage.setItem('neon-alley-best',String(best));}catch{}const won=mode==='won';showModal(won?'TRANSMISSION RESTORED':'THE NIGHT IS NOT OVER',won?'街區，重新發聲。':'倒下，再站起來。',won?`RIN 接通了最後一座中繼站。窗裡的燈，一盞接一盞亮起。\n最終分數 ${game.score} · 最高連段 ${game.bestCombo||0}\n謝謝你，把聲音還給這座城市。`:`你在 ${game.stageName} 倒下。\n分數 ${game.score} · 試著上下閃避預警，或切換輕鬆難度再出發。`);$('pause').disabled=true;$('replay').focus({preventScroll:true});refreshHUD();}
function refreshHUD(){const p=game.player,ratio=Math.max(0,p.hp/p.maxHp);$('health-fill').style.width=`${ratio*100}%`;$('health-fill').style.background=ratio<.3?'#ff6e69':'#91f7cd';$('hp').textContent=`${Math.ceil(p.hp)} / ${p.maxHp}`;const bar=document.querySelector('.health-track');bar.setAttribute('aria-valuenow',Math.ceil(p.hp));bar.setAttribute('aria-valuemax',p.maxHp);$('stage-label').textContent=game.stageName||'AFTERGLOW AVENUE';$('wave-label').textContent=`ACT 0${game.stage+1} / WAVE 0${game.wave+1}`;$('score').textContent=String(game.score).padStart(6,'0');$('best').textContent=`BEST ${String(Math.max(best,game.score)).padStart(6,'0')}`;const enemies=game.enemies.filter(e=>!e.dead).length;$('status').textContent=mode==='title'?'THE SIGNAL IS WAITING. / 等你出發':mode==='paused'?'PAUSED / 已暫停':mode==='won'?'SIGNAL RESTORED / 任務完成':mode==='lost'?'SIGNAL LOST / 再試一次':game.transition>0?'AREA CLEAR / 街區推進中':`ENEMIES ${enemies} · ${game.combo>1?game.combo+' HIT COMBO':'保持移動，找準時機'}`;canvas.dataset.state=mode;canvas.dataset.stage=game.stage;canvas.dataset.wave=game.wave;canvas.dataset.hp=p.hp;canvas.dataset.score=game.score;canvas.dataset.audio=audio.ctx?.state||'locked';canvas.dataset.notes=audio.notes;canvas.dataset.voices=audio.voices;}
function frame(now){const elapsed=Math.min(.1,Math.max(0,(now-last)/1000));last=now;if(mode==='playing'){accumulator+=elapsed;while(accumulator>=1/60){update(game,1/60,input());for(const event of game.events||[]){if(event.type==='sound')audio.effect(event.kind);}accumulator-=1/60;if(game.status!=='playing'){finish();break;}}audio.tick(game.stage);tipTimer-=elapsed;if(game.grabTarget)$('combat-tip').textContent='敵人暈眩！靠近按 L 抓摔';else if(tipTimer<=0)$('combat-tip').textContent='';}render(ctx,game,{reducedMotion:reduced.matches});hudTime+=elapsed;if(hudTime>.12){refreshHUD();hudTime=0;}requestAnimationFrame(frame);}
$('start').onclick=start;$('replay').onclick=start;$('resume').onclick=pause;$('menu').onclick=title;$('pause').onclick=pause;$('mute').onclick=mute;$('help').onclick=()=>{const open=$('guide').hidden;$('guide').hidden=!open;$('help').setAttribute('aria-expanded',String(open));if(mode==='playing')pause();};
window.addEventListener('keydown',e=>{if(['SELECT','INPUT','TEXTAREA'].includes(e.target.tagName))return;if(mapping[e.code]&&mode==='playing'){e.preventDefault();keys.add(mapping[e.code]);}if(!e.repeat&&['KeyP','Escape'].includes(e.code)){e.preventDefault();pause();}if(!e.repeat&&e.code==='KeyM')mute();});
window.addEventListener('keyup',e=>{if(mapping[e.code]){keys.delete(mapping[e.code]);if(mode==='playing')e.preventDefault();}});
window.addEventListener('blur',()=>{clearInput();if(mode==='playing')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInput();if(mode==='playing')pause();}});
for(const b of document.querySelectorAll('[data-control]')){b.addEventListener('pointerdown',e=>{e.preventDefault();if(mode!=='playing')return;audio.unlock();b.setPointerCapture(e.pointerId);touches.set(e.pointerId,b.dataset.control);b.classList.add('held');});for(const type of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(type,e=>{touches.delete(e.pointerId);if(![...touches.values()].includes(b.dataset.control))b.classList.remove('held');});b.addEventListener('contextmenu',e=>e.preventDefault());}
soundLabel();refreshHUD();requestAnimationFrame(frame);
