// All melodies, synthesis and sound effects are original. No audio files are fetched.
export class AudioSystem {
  constructor(){this.ctx=null;this.master=null;this.muted=false;this.running=false;this.next=0;this.step=0;this.notes=0;this.voices=0;}
  unlock(){try{if(!this.ctx){const C=globalThis.AudioContext||globalThis.webkitAudioContext;if(!C)return;this.ctx=new C();this.master=this.ctx.createGain();this.master.gain.value=this.muted?0:.18;this.master.connect(this.ctx.destination);}if(this.ctx.state==='suspended')this.ctx.resume()?.catch(()=>{});}catch{this.ctx=null;}}
  setMuted(value){this.muted=value;if(this.master)this.master.gain.setValueAtTime(value?0:.18,this.ctx.currentTime);}
  setRunning(value){this.running=value;this.next=this.ctx?.currentTime||0;if(!value&&this.master)this.master.gain.setValueAtTime(this.muted?0:.12,this.ctx.currentTime);else if(this.master)this.master.gain.setValueAtTime(this.muted?0:.18,this.ctx.currentTime);}
  tone(freq,duration=.1,type='square',volume=.12,at){if(!this.ctx||this.muted)return;const t=at??this.ctx.currentTime;const osc=this.ctx.createOscillator(),gain=this.ctx.createGain();osc.type=type;osc.frequency.setValueAtTime(freq,t);gain.gain.setValueAtTime(.0001,t);gain.gain.exponentialRampToValueAtTime(Math.max(.001,volume),t+.008);gain.gain.exponentialRampToValueAtTime(.0001,t+duration);osc.connect(gain);gain.connect(this.master);osc.start(t);osc.stop(t+duration+.02);osc.onended=()=>{osc.disconnect();gain.disconnect();this.voices--;};this.notes++;this.voices++;}
  tick(stage=0){if(!this.ctx||!this.running||this.muted)return;const now=this.ctx.currentTime;if(this.next<now-.4)this.next=now;const melody=[0,7,10,14,12,7,3,5,0,10,7,3,5,12,10,7];const roots=[110,123.47,130.81];let guard=0;while(this.next<now+.1&&guard++<3){const s=this.step++%32,root=roots[stage]||110;this.tone(root*Math.pow(2,melody[s%16]/12),.14,'triangle',.15,this.next);if(s%4===0)this.tone(root/2,.2,'triangle',.35,this.next);if(s%2===0)this.tone(s%4===0?65:1600,.035,'square',.035,this.next);this.next+=.17;}}
  effect(kind){if(!this.ctx||this.muted)return;const map={punch:[190,.07,'triangle'],kick:[120,.10,'sawtooth'],hit:[70,.1,'square'],hurt:[85,.16,'sawtooth'],jump:[350,.08,'triangle'],throw:[90,.18,'sawtooth'],ko:[55,.18,'square'],pickup:[660,.17,'sine'],wave:[440,.17,'triangle'],stage:[550,.22,'triangle'],win:[880,.4,'triangle'],lose:[110,.4,'triangle']};const s=map[kind];if(s)this.tone(...s,.17);}
}
